import { readFile, writeFile } from "node:fs/promises"
import { createRequire } from "node:module"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"

import { SITE_ICON_OPTIONS } from "../src/site-icons"

const require = createRequire(import.meta.url)
const scriptDirectory = dirname(fileURLToPath(import.meta.url))
const outputPath = resolve(scriptDirectory, "../src/site-icon-svg-bodies.generated.ts")

const entries = await Promise.all(SITE_ICON_OPTIONS.map(async ({ name, tablerName }) => {
  const svgPath = require.resolve(`@tabler/icons/outline/${tablerName}.svg`)
  const svg = await readFile(svgPath, "utf8")
  const body = svg.match(/<svg[^>]*>([\s\S]*?)<\/svg>/)?.[1]?.trim()
  if (!body) throw new Error(`Could not extract Tabler icon ${tablerName}`)
  return [name, body.replace(/>\s+</g, "><")] as const
}))

const source = `// Generated by scripts/generate-site-icons.ts from @tabler/icons.\nexport const SITE_ICON_SVG_BODIES = ${JSON.stringify(Object.fromEntries(entries), null, 2)} as const\n`
await writeFile(outputPath, source)
