import { SITE_MOBILE_BREAKPOINT_PX } from "@handout/design-tokens";

/**
 * Canonical visual contract for editable, previewed, and published site content.
 * Keep editor-only affordances out of this stylesheet.
 */
export const SITE_DOCUMENT_CSS = `
[data-handout-public-site],[data-handout-public-site] *,.handout-document-editor,.handout-document-editor *{box-sizing:border-box}
.handout-privacy-choices{position:fixed;right:12px;bottom:12px;z-index:69;padding:6px 9px;border:1px solid var(--border);border-radius:8px;background:var(--background);color:var(--muted-foreground);font:500 12px/16px "Geist Variable","Geist",ui-sans-serif,system-ui,sans-serif;box-shadow:0 1px 3px rgba(0,0,0,.08);cursor:pointer}.handout-privacy-choices:hover,.handout-privacy-choices:focus-visible{color:var(--foreground);outline:0}.handout-privacy-choices[hidden],.handout-consent-popup[hidden]{display:none}
html[data-handout-public-site],body[data-handout-public-site]{margin:0;min-height:100%;background:var(--background);color:var(--foreground);font-family:"Geist Variable","Geist",ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;letter-spacing:-.02em}
:where(.handout-site) button,:where(.handout-site) a{font:inherit}:where(.handout-site) a{color:inherit}
.handout-site,.handout-document-editor{--handout-font-weight-body:400;--handout-font-weight-heading:550;--handout-font-weight-label:500;--handout-block-gap:20px;--handout-body-gap:12px;--handout-heading-body-gap:14px;--handout-list-block-gap:24px;--handout-heading-1-gap:72px;--handout-heading-2-gap:50px;--handout-heading-3-gap:36px;--handout-divider-gap:36px;--handout-list-item-gap:4px;background:var(--background);color:var(--foreground);font-family:"Geist Variable","Geist",ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;letter-spacing:-.02em}
:where(html[data-handout-public-site],body[data-handout-public-site],.handout-site,.handout-document-editor,.handout-editor-sidebar-content),:where(.handout-site,.handout-document-editor,.handout-editor-sidebar-content) *{font-feature-settings:normal;font-kerning:normal;font-optical-sizing:auto;font-synthesis-weight:none;text-rendering:optimizeLegibility;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale}
.handout-site{display:flex;min-height:100svh}
.handout-sidebar{position:sticky;top:0;display:flex;width:289px;height:100svh;flex:none;flex-direction:column;gap:24px;padding:26px 24px 20px;background:var(--background)}
.handout-sidebar-inner{display:flex;width:241px;min-height:0;flex:1;flex-direction:column;gap:24px;overflow-y:auto}
.handout-sidebar-mobile-header,.handout-sidebar-backdrop{display:none}
.handout-editor-sidebar-desktop{display:flex}.handout-editor-mobile-bar{display:none}.handout-editor-sidebar-content{width:241px}.handout-sidebar,.handout-editor-sidebar-content{font-family:"Geist Variable","Geist",ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;font-weight:400;letter-spacing:-.02em}.handout-editor-sidebar-content :where(button,a){font-family:inherit;letter-spacing:-.02em}
.handout-sidebar-built-with{display:flex;width:100%;flex:none;align-items:center;justify-content:center;gap:6px;color:var(--tertiary-foreground);font-size:14px;font-weight:400;letter-spacing:-.02em;line-height:24px;white-space:nowrap}.handout-sidebar-built-with-logo{display:block;width:12px;height:13px;flex:none;background:var(--tertiary-foreground);-webkit-mask:url("/handout-logo-icon.svg") center/contain no-repeat;mask:url("/handout-logo-icon.svg") center/contain no-repeat}.handout-sidebar-built-with a{color:inherit;text-decoration:underline;text-decoration-skip-ink:none;text-underline-position:from-font}
/* PUBLISHED-SITE PARITY: Keep these sidebar rules aligned with EditorSiteSidebar.
   Preview and deployed sites both consume this canonical stylesheet. */
.handout-sidebar-section{display:flex;min-width:0;flex-direction:column;gap:8px}.handout-sidebar-section>h2,.handout-editor-sidebar-section-title{height:26px;min-width:0;margin:0 0 0 4px;overflow:hidden;color:var(--foreground);font-size:14px;font-weight:500;letter-spacing:-.02em;line-height:24px;text-overflow:ellipsis;white-space:nowrap}.handout-sidebar-section-buttons{gap:10px}
.handout-sidebar-section>div{display:flex;flex-direction:column;gap:4px}
.handout-sidebar-row{display:flex;width:100%;height:36px;align-items:center;gap:8px;padding:0 10px;border:0;border-radius:8px;background:transparent;color:var(--foreground);font-size:16px;font-weight:400;letter-spacing:-.02em;line-height:24px;text-align:left;text-decoration:none;cursor:pointer;transition:background .15s ease}
.handout-sidebar-row:hover,.handout-sidebar-row:focus-visible{background:var(--accent);outline:0}.handout-sidebar-row.is-active{background:var(--handout-primary-soft,var(--accent));outline:0}.handout-tab,.handout-sidebar-link{color:var(--tertiary-foreground)}.handout-sidebar-link:hover,.handout-sidebar-link:focus-visible{color:var(--foreground)}.handout-sidebar-row.is-active{color:var(--handout-primary,var(--foreground))}.handout-sidebar-row svg{width:16px;height:16px;flex:none;color:var(--tertiary-foreground)}.handout-sidebar-link svg{color:var(--handout-sidebar-link-icon,var(--blue-foreground))}.handout-tab svg{color:var(--muted-foreground)}.handout-sidebar-row.is-active svg{color:inherit}.handout-sidebar-row span{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.handout-sidebar-button{display:flex;min-height:36px;align-items:center;justify-content:center;gap:6px;padding:6px 12px;border:1px solid var(--border);border-radius:10px;font-size:15px;font-weight:500;letter-spacing:-.02em;line-height:20px;text-align:center;text-decoration:none;transition:background .15s ease}.handout-sidebar-button>svg{width:15px;height:15px;flex:none}.handout-editor-sidebar-button{letter-spacing:-.02em}
.handout-sidebar-button-filled{border-color:transparent;background:var(--handout-primary,var(--primary));color:var(--handout-primary-foreground,var(--primary-foreground))}.handout-sidebar-button-outline{background:var(--background)}.handout-sidebar-button:hover{filter:brightness(.94)}
.handout-sidebar-section-buttons>div{gap:8px}
.handout-main{display:flex;min-width:0;min-height:100svh;flex:1;flex-direction:column}.handout-mobile-bar{display:none}.handout-document{width:100%;flex:1;padding:54px 52px 128px}
.handout-document,.handout-document-editor{font-weight:var(--handout-font-weight-body)}
.handout-page-panel{width:612px;max-width:100%;margin:0 auto;container-type:inline-size}.handout-page-panel:focus{outline:0}.handout-page-panel[hidden]{display:none}
.handout-prosemirror{min-height:100%;outline:none}.handout-prosemirror>*{width:100%;margin:0}
.handout-prosemirror strong{font-weight:700}
.handout-paragraph,.handout-prosemirror>p,.handout-grid-cell>p,.handout-document-editor .handout-grid-cell>p{margin:0;padding:0;color:var(--tertiary-foreground);font-size:16px;font-weight:var(--handout-font-weight-body);line-height:26px;white-space:pre-wrap}
.handout-heading-1,.handout-prosemirror>h1,.handout-grid-cell>h1,.handout-document-editor .handout-grid-cell>h1{margin:0;padding:0;color:var(--foreground);font-size:24px;font-weight:var(--handout-font-weight-heading);letter-spacing:-.03em;line-height:36px;white-space:pre-wrap}
.handout-heading-2,.handout-prosemirror>h2,.handout-grid-cell>h2,.handout-document-editor .handout-grid-cell>h2{margin:0;padding:0;color:var(--foreground);font-size:20px;font-weight:var(--handout-font-weight-heading);letter-spacing:-.03em;line-height:32px;white-space:pre-wrap}
.handout-heading-3,.handout-prosemirror>h3,.handout-grid-cell>h3,.handout-document-editor .handout-grid-cell>h3{margin:0;padding:0;color:var(--foreground);font-size:16px;font-weight:var(--handout-font-weight-heading);letter-spacing:-.03em;line-height:26px;white-space:pre-wrap}
.handout-list,.handout-prosemirror>ul,.handout-prosemirror>ol,.handout-grid-cell>ul,.handout-grid-cell>ol,.handout-document-editor .handout-grid-cell>ul,.handout-document-editor .handout-grid-cell>ol{margin:0;padding:0 0 0 24px;color:var(--tertiary-foreground);font-size:16px;font-weight:var(--handout-font-weight-body);line-height:26px}.handout-prosemirror>ul,.handout-grid-cell>ul{list-style:disc}.handout-prosemirror>ol,.handout-grid-cell>ol{list-style:decimal}.handout-list-item,.handout-document-editor .handout-prosemirror>:where(ul,ol)>li{padding-left:0}.handout-list:is(ol)>.handout-list-item,.handout-document-editor .handout-prosemirror>ol>li{padding-left:2px}.handout-list>.handout-list-item+.handout-list-item,.handout-document-editor .handout-prosemirror :where(ul:not([data-type=taskList]):not([data-handout-icon-list]),ol)>li+li{margin-top:var(--handout-list-item-gap)}.handout-prosemirror li p,.handout-list-item p{margin:0}
.handout-blockquote,.handout-prosemirror>blockquote,.handout-grid-cell>blockquote{margin:0;padding:6px 0 6px 16px;border-left:4px solid var(--border);color:var(--muted-foreground);font-size:16px;font-weight:var(--handout-font-weight-body);line-height:26px}.handout-blockquote p,.handout-prosemirror>blockquote p,.handout-grid-cell>blockquote p{margin:0}
.handout-task-list,.handout-document-editor .handout-prosemirror ul[data-type=taskList]{display:flex;flex-direction:column;gap:var(--handout-list-item-gap);padding:0!important;list-style:none!important}.handout-task-item{display:flex;align-items:flex-start;gap:8px}.handout-task-check{display:flex;width:16px;height:16px;flex:none;align-items:center;justify-content:center;margin-top:5px;border:1px solid var(--border);border-radius:4px;font-size:11px}.handout-task-item[data-checked=true]>div{color:var(--muted-foreground);text-decoration:line-through}
.handout-code-block,.handout-prosemirror>pre,.handout-grid-cell>pre{margin:0;overflow:auto;padding:16px;border:1px solid var(--border);border-radius:8px;background:var(--muted);color:var(--foreground);font-size:14px;font-weight:var(--handout-font-weight-body);line-height:24px}.handout-code-block code,.handout-prosemirror>pre code,.handout-grid-cell>pre code{display:block;padding:0;border:0;background:transparent;color:inherit;font:inherit}.handout-inline-code,.handout-document-editor .handout-prosemirror code:not(pre code){padding:2px 6px;border:1px solid var(--border);border-radius:6px;background:var(--muted);color:var(--foreground);font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:.875em;font-weight:var(--handout-font-weight-body);line-height:normal}
.handout-divider{height:24px;margin:0;border:0;background:linear-gradient(to bottom,transparent calc(50% - .5px),var(--border) calc(50% - .5px),var(--border) calc(50% + .5px),transparent calc(50% + .5px))}
.handout-page-title{display:flex;flex-direction:column;align-items:center;gap:24px;padding:0 0 36px;border-bottom:1px solid var(--border);text-align:center}.handout-page-title[data-align=left]{align-items:flex-start;text-align:left}
.handout-page-title-logos{display:flex;flex-wrap:wrap;align-items:center;justify-content:center;gap:8px}.handout-page-title[data-align=left] .handout-page-title-logos{justify-content:flex-start}
.handout-page-title-logo{display:flex;width:52px;height:52px;align-items:center;justify-content:center;overflow:hidden;border:1px solid var(--border);border-radius:14px;background:var(--background);color:var(--foreground)}.handout-page-title-logo img{width:100%;height:100%;padding:0;object-fit:cover}.handout-logo-connector{display:none}
.handout-page-title-copy{width:100%}.handout-page-title-heading,[data-handout-page-title-heading]{max-width:100%;margin:0;color:var(--foreground);font-size:28px;font-weight:var(--handout-font-weight-heading);letter-spacing:-.03em;line-height:1}.handout-page-title-subtitle,[data-handout-page-title-subtitle]{max-width:100%;margin:8px 0 0;color:var(--tertiary-foreground);font-size:16px;font-weight:var(--handout-font-weight-body);letter-spacing:-.02em;line-height:1.5}
.handout-icon-list,.handout-document-editor .handout-prosemirror ul[data-handout-icon-list]{display:flex;flex-direction:column;gap:var(--handout-list-item-gap);padding:0!important;list-style:none!important}.handout-document-editor .handout-prosemirror li[data-handout-icon-list-item],.handout-document-editor .handout-prosemirror li[data-handout-icon-list-item]::marker{list-style:none}.handout-document-editor .handout-prosemirror li[data-handout-icon-list-item]::marker{content:""}.handout-icon-list-item{display:grid;grid-template-columns:20px minmax(0,1fr);align-items:start;gap:2px;padding-left:4px}.handout-icon-list-item>div{min-width:0;color:var(--tertiary-foreground);font-size:16px;line-height:26px}.handout-icon-tile{display:flex;width:20px;height:20px;align-items:center;justify-content:center;margin-top:3px;color:var(--muted-foreground)}.handout-icon-tile svg{width:14px;height:14px}
[data-icon-color=neutral]{--handout-icon-color:var(--color-muted-foreground,var(--muted-foreground));--handout-icon-background:var(--color-muted,var(--muted));color:var(--handout-icon-color)}[data-icon-color=purple]{--handout-icon-color:var(--color-purple-foreground,var(--purple-foreground));--handout-icon-background:var(--color-purple-background,var(--purple-background));color:var(--handout-icon-color)}[data-icon-color=blue]{--handout-icon-color:var(--color-blue-foreground,var(--blue-foreground));--handout-icon-background:var(--color-blue-background,var(--blue-background));color:var(--handout-icon-color)}[data-icon-color=cyan]{--handout-icon-color:var(--color-cyan-foreground,var(--cyan-foreground));--handout-icon-background:var(--color-cyan-background,var(--cyan-background));color:var(--handout-icon-color)}[data-icon-color=teal]{--handout-icon-color:var(--color-teal-foreground,var(--teal-foreground));--handout-icon-background:var(--color-teal-background,var(--teal-background));color:var(--handout-icon-color)}[data-icon-color=green]{--handout-icon-color:var(--color-green-foreground,var(--green-foreground));--handout-icon-background:var(--color-green-background,var(--green-background));color:var(--handout-icon-color)}[data-icon-color=yellow]{--handout-icon-color:var(--color-yellow-foreground,var(--yellow-foreground));--handout-icon-background:var(--color-yellow-background,var(--yellow-background));color:var(--handout-icon-color)}[data-icon-color=orange]{--handout-icon-color:var(--color-orange-foreground,var(--orange-foreground));--handout-icon-background:var(--color-orange-background,var(--orange-background));color:var(--handout-icon-color)}[data-icon-color=red]{--handout-icon-color:var(--color-red-foreground,var(--red-foreground));--handout-icon-background:var(--color-red-background,var(--red-background));color:var(--handout-icon-color)}[data-icon-color=pink]{--handout-icon-color:var(--color-pink-foreground,var(--pink-foreground));--handout-icon-background:var(--color-pink-background,var(--pink-background));color:var(--handout-icon-color)}
.handout-image-block{overflow:hidden;border-radius:10px}.handout-image-block img{display:block;width:100%;height:auto;max-height:680px;object-fit:contain}.handout-document-editor .handout-editor-image,.handout-document-editor .handout-editor-gif{display:block;height:auto;max-width:100%;max-height:680px;border:0;border-radius:10px;background:transparent;object-fit:contain}
.handout-image-card{display:grid;grid-template-columns:minmax(180px,41.5%) minmax(0,1fr);align-items:center;gap:20px;overflow:hidden;padding:6px;border:1px solid var(--site-card-border);border-radius:14px;background:var(--site-card-background);color:var(--foreground);box-shadow:var(--shadow-xs)}.handout-image-card-media{display:block;align-self:center;overflow:hidden;border-radius:10px;line-height:0}.handout-image-card-media img{display:block;width:100%;height:auto;border-radius:10px;object-fit:contain}.handout-image-card-copy{display:flex;min-width:0;flex-direction:column;align-items:flex-start;justify-content:center;padding:20px}.handout-card-title,[data-handout-icon-card-title],[data-handout-image-card-title]{margin:0;color:var(--foreground);font-size:16px;font-weight:var(--handout-font-weight-heading);line-height:24px}.handout-card-body,[data-handout-icon-card-body],[data-handout-image-card-body]{margin:0;color:var(--tertiary-foreground);font-size:14px;font-weight:var(--handout-font-weight-body);line-height:24px}.handout-small-button{display:inline-flex;width:max-content;height:30px;align-items:center;justify-content:center;margin-top:12px;padding:0 10px;border:1px solid var(--border);border-radius:8px;color:var(--foreground);font-size:14px;font-weight:var(--handout-font-weight-label);text-decoration:none}
.handout-icon-card{padding:16px;border:1px solid var(--site-card-border);border-radius:14px;background:var(--site-card-background);color:var(--foreground);box-shadow:var(--shadow-xs)}.handout-card-icon{display:flex;width:32px;height:32px;align-items:center;justify-content:center;margin-bottom:12px;border-radius:8px;background:var(--handout-icon-background,var(--color-muted,var(--muted)));color:var(--handout-icon-color,var(--color-muted-foreground,var(--muted-foreground)))}.handout-card-icon svg{width:18px;height:18px}.handout-card-copy{min-width:0}.handout-card-title,[data-handout-icon-card-title],[data-handout-image-card-title],.handout-logo-grid-title,[data-handout-logo-grid-title]{letter-spacing:-.03em}
.handout-testimonial{display:grid;grid-template-columns:40px minmax(0,1fr);grid-template-rows:20px 20px minmax(40px,auto);column-gap:12px;align-items:center;padding:16px 20px 20px 16px;border:1px solid var(--site-card-border);border-radius:14px;background:var(--site-card-background);color:var(--foreground);box-shadow:var(--shadow-xs)}.handout-testimonial-avatar{display:flex;width:40px;height:40px;align-items:center;justify-content:center;overflow:hidden;grid-column:1;grid-row:1 / span 2;border:1px solid var(--border);border-radius:10px;background:var(--muted)}.handout-testimonial-avatar img{width:100%;height:100%;object-fit:cover}.handout-testimonial-avatar svg{width:18px;height:18px}.handout-testimonial>div{display:contents}.handout-testimonial-name,[data-handout-testimonial-author-name]{min-width:0;margin:0;overflow:hidden;grid-column:2;grid-row:1;color:var(--foreground);font-size:16px;font-weight:var(--handout-font-weight-label);line-height:20px;text-overflow:ellipsis;white-space:nowrap}.handout-testimonial-role,[data-handout-testimonial-author-role]{min-width:0;margin:0;overflow:hidden;grid-column:2;grid-row:2;color:var(--tertiary-foreground);font-size:14px;font-weight:var(--handout-font-weight-body);line-height:20px;text-overflow:ellipsis;white-space:nowrap}.handout-testimonial-quote,[data-handout-testimonial-quote]{min-height:40px;margin:0;padding-top:16px;grid-column:1 / -1;grid-row:3;color:var(--foreground);font-size:18px;font-weight:var(--handout-font-weight-heading);line-height:24px}.handout-testimonial-quote:before,[data-handout-testimonial-quote]:before{content:"\\201C"}.handout-testimonial-quote:after,[data-handout-testimonial-quote]:after{content:"\\201D"}
.handout-logo-grid{display:grid;width:100%;min-width:0;max-width:100%;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;padding:0}.handout-logo-grid-item{display:flex;min-width:0;flex-direction:column;align-items:center;gap:8px;padding:16px 12px 12px;border:1px solid var(--site-card-border);border-radius:14px;background:var(--site-card-background);color:var(--foreground);text-align:center;box-shadow:var(--shadow-xs)}.handout-logo-grid-image{display:flex;width:40px;height:40px;align-items:center;justify-content:center;overflow:hidden;border-radius:10px}.handout-logo-grid-image img{width:100%;height:100%;object-fit:contain}.handout-logo-grid-image svg{width:20px;height:20px}.handout-logo-grid-title,[data-handout-logo-grid-title]{margin:0;color:var(--foreground);font-size:16px;font-weight:var(--handout-font-weight-heading);line-height:24px}
.handout-button-block{display:inline-flex;width:max-content;min-height:32px;max-width:100%;align-items:center;justify-content:center;padding:0 12px;border-radius:8px;background:var(--handout-primary,var(--primary));color:var(--handout-primary-foreground,var(--primary-foreground));font-size:15px;font-weight:var(--handout-font-weight-label);line-height:20px;text-align:center;text-decoration:none;box-shadow:0 0 0 1px color-mix(in oklab,var(--handout-primary,var(--primary)) 16%,transparent)}.handout-button-block:hover{background:color-mix(in oklab,var(--handout-primary,var(--primary)) 88%,var(--background))}.handout-button-block-full{display:flex;width:100%;min-height:40px;padding:2px 12px}
.handout-embed{width:100%;overflow:hidden;border:1px solid var(--site-card-border);border-radius:12px;background:var(--site-card-background);box-shadow:var(--shadow-xs)}.handout-embed iframe{width:100%;height:100%;border:0}
.handout-grid{display:flex;flex-direction:column;gap:12px}.handout-grid-row{display:grid;grid-template-columns:repeat(var(--handout-grid-columns),minmax(0,1fr));gap:12px}.handout-grid-cell,.handout-document-editor .handout-grid-cell{min-width:0;padding:0;border:0;background:transparent;box-shadow:none}.handout-grid-cell>*+*{margin-top:12px}
.handout-page-navigation{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;margin-top:64px}.handout-page-navigation-link{display:flex;min-width:0;min-height:76px;align-items:center;gap:12px;padding:14px 16px;border:1px solid var(--site-card-border);border-radius:14px;background:var(--site-card-background);color:var(--foreground);font:inherit;text-align:left;cursor:pointer;box-shadow:var(--shadow-xs);transition:border-color .15s ease,background .15s ease,transform .15s ease}.handout-page-navigation-link:hover{border-color:var(--border-strong,var(--site-card-border));background:var(--accent)}.handout-page-navigation-link:focus-visible{border-color:var(--ring);outline:3px solid color-mix(in oklab,var(--ring) 35%,transparent);outline-offset:2px}.handout-page-navigation-link:active{transform:translateY(1px)}.handout-page-navigation-link>svg{width:18px;height:18px;flex:none;color:var(--muted-foreground)}.handout-page-navigation-copy{display:flex;min-width:0;flex:1;flex-direction:column}.handout-page-navigation-label{color:var(--muted-foreground);font-size:12px;font-weight:var(--handout-font-weight-label);line-height:18px}.handout-page-navigation-name{min-width:0;overflow:hidden;color:var(--foreground);font-size:15px;font-weight:var(--handout-font-weight-label);line-height:22px;text-overflow:ellipsis;white-space:nowrap}.handout-page-navigation-next{grid-column:2;text-align:right}.handout-page-navigation-next .handout-page-navigation-copy{align-items:flex-end}.handout-page-navigation-link:hover>svg,.handout-page-navigation-link:focus-visible>svg{color:var(--foreground)}
@container (max-width:520px){.handout-image-card{grid-template-columns:1fr;gap:0}.handout-image-card-copy{min-height:80px;padding:16px}.handout-logo-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.handout-grid-row{grid-template-columns:1fr}}
@container (max-width:520px){.handout-page-navigation{grid-template-columns:1fr;gap:8px}.handout-page-navigation-next{grid-column:1}}
@container (max-width:340px){.handout-logo-grid{grid-template-columns:1fr}}
.handout-table-scroll,.handout-document-editor .tableWrapper{overflow-x:auto;border:0;border-radius:10px;background:transparent;box-shadow:var(--shadow-xs)}.handout-table,.handout-document-editor .tableWrapper>table{width:100%;border:1px solid var(--site-card-border);border-collapse:separate;border-spacing:0;border-radius:10px;background:var(--site-card-background);color:var(--foreground);font-size:14px;font-weight:var(--handout-font-weight-body);line-height:22px}.handout-table th,.handout-table td,.handout-document-editor .tableWrapper>table th,.handout-document-editor .tableWrapper>table td{min-width:112px;padding:10px 12px;border-top:0;border-left:0;border-right:1px solid var(--site-card-border);border-bottom:1px solid var(--site-card-border);color:var(--tertiary-foreground);font-size:14px;font-weight:var(--handout-font-weight-body);line-height:22px;text-align:left;vertical-align:top}.handout-table th,.handout-document-editor .tableWrapper>table th{background:var(--table-header-background);color:var(--foreground);font-weight:var(--handout-font-weight-label)}.handout-table tr>*:last-child,.handout-document-editor .tableWrapper>table tr>*:last-child{border-right:0}.handout-table tr:last-child>*,.handout-document-editor .tableWrapper>table tr:last-child>*{border-bottom:0}.handout-table :where(th,td)>*,.handout-document-editor .tableWrapper>table :where(th,td)>*{margin:0}
.handout-link,.handout-document-editor .handout-prosemirror a:not(.handout-editor-image-card-cta){color:var(--link);text-underline-offset:2px}.handout-empty-page{padding:80px 0;text-align:center}.handout-empty-page h1{font-size:20px}
.handout-consent-popup{position:fixed;z-index:50;inset:0;display:grid;place-items:center;padding:16px;background:rgb(0 0 0 / 20%);font-family:"Geist Variable","Geist",ui-sans-serif,system-ui,sans-serif;letter-spacing:-.02em}.handout-consent-dialog{display:flex;width:min(458px,100%);flex-direction:column;gap:20px;padding:10px 16px 16px;border-radius:18px;background:var(--popover);color:var(--popover-foreground);box-shadow:0 16px 48px rgb(0 0 0 / 16%),0 0 0 1px rgb(0 0 0 / 5%)}.handout-consent-copy{display:flex;flex-direction:column}.handout-consent-dialog h2{margin:0;padding:6px 0;font-size:16px;font-weight:500;line-height:24px}.handout-consent-dialog p{margin:0;color:var(--tertiary-foreground);font-size:13px;font-weight:400;line-height:20px}.handout-consent-dialog p a,.handout-consent-dialog p button{padding:0;border:0;background:none;color:inherit;font:inherit;text-decoration:underline;text-underline-offset:2px;cursor:pointer}.handout-consent-actions{display:flex;gap:6px}.handout-consent-button{display:flex;height:32px;min-width:0;flex:1;align-items:center;justify-content:center;padding:0 10px;border:1px solid var(--border);border-radius:10px;background:var(--background);color:var(--muted-foreground);font-size:14px;font-weight:500;cursor:pointer}.handout-consent-button-primary{border-color:transparent;background:var(--handout-primary,var(--primary));color:var(--handout-primary-foreground,var(--primary-foreground));box-shadow:0 1px 1px rgb(0 0 0 / 5%)}
/* Canonical root block rhythm. Relationships select one shared token; this final resolver wins after component resets in every renderer. */
.handout-prosemirror>p+p{--handout-sibling-gap:var(--handout-body-gap)}
.handout-prosemirror>h1+p,.handout-prosemirror>h2+p,.handout-prosemirror>h3+p{--handout-sibling-gap:var(--handout-heading-body-gap)}
.handout-prosemirror>blockquote,.handout-prosemirror>pre,.handout-prosemirror>ul,.handout-prosemirror>ol,.handout-prosemirror>:where(ul,ol)+*{--handout-sibling-gap:var(--handout-list-block-gap)}
.handout-prosemirror>h1{--handout-sibling-gap:var(--handout-heading-1-gap)}.handout-prosemirror>h2{--handout-sibling-gap:var(--handout-heading-2-gap)}.handout-prosemirror>h3{--handout-sibling-gap:var(--handout-heading-3-gap)}
.handout-prosemirror>hr{--handout-sibling-gap:var(--handout-divider-gap)}
.handout-prosemirror>:not(:first-child){margin-top:var(--handout-sibling-gap,var(--handout-block-gap))}
/* The editor uses richer node-view wrappers, but the presentation contract remains identical. */
.handout-document-editor .handout-prosemirror{width:100%;min-width:0;max-width:100%;padding-top:54px;padding-bottom:128px}.handout-document-editor[data-has-page-navigation] .handout-prosemirror{padding-bottom:0}.handout-editor-page-navigation{width:min(612px,calc(100% - 104px));max-width:calc(100% - 104px);margin:64px auto 0;padding-bottom:128px}
.handout-document-editor .handout-prosemirror>p,.handout-document-editor .handout-prosemirror>h1,.handout-document-editor .handout-prosemirror>h2,.handout-document-editor .handout-prosemirror>h3,.handout-document-editor .handout-prosemirror>ul,.handout-document-editor .handout-prosemirror>ol,.handout-document-editor .handout-prosemirror>blockquote,.handout-document-editor .handout-prosemirror>pre,.handout-document-editor .handout-prosemirror>hr,.handout-document-editor .handout-prosemirror>.react-renderer,.handout-document-editor .handout-prosemirror>[data-handout-grid],.handout-document-editor .handout-prosemirror>.tableWrapper,.handout-document-editor .handout-prosemirror>table,.handout-document-editor .handout-prosemirror>[data-handout-gif-empty],.handout-document-editor .handout-prosemirror>[data-handout-image-empty],.handout-document-editor .handout-prosemirror>[data-resize-container][data-node=gifBlock],.handout-document-editor .handout-prosemirror>[data-resize-container][data-node=image]{width:min(612px,calc(100% - 104px));max-width:calc(100% - 104px);margin-right:auto;margin-left:auto}
.handout-document-editor .handout-editor-page-title{display:contents}.handout-document-editor .handout-editor-page-title-content>[data-node-view-content-react],.handout-document-editor .handout-editor-logo-grid>[data-node-view-content-react]{display:contents}
@media(max-width:${SITE_MOBILE_BREAKPOINT_PX}px){.handout-editor-sidebar-desktop{display:none}.handout-editor-mobile-bar{display:flex}.handout-editor-sidebar-content{width:100%}body.handout-drawer-open{overflow:hidden}.handout-site{display:block}.handout-sidebar{position:fixed;z-index:30;top:0;left:0;width:min(289px,86vw);height:100svh;gap:0;padding:0;border-right:1px solid var(--border);background:var(--background);box-shadow:0 16px 40px rgb(0 0 0 / 18%);visibility:hidden;transform:translateX(-100%);transition:transform .2s ease,visibility .2s ease}.handout-sidebar.is-open{visibility:visible;transform:translateX(0)}.handout-sidebar-mobile-header{display:flex;height:44px;align-items:center;gap:8px;padding:0 8px 0 16px;border-bottom:1px solid var(--border-subtle)}.handout-sidebar-mobile-title{min-width:0;flex:1;overflow:hidden;color:var(--tertiary-foreground);font-size:16px;font-weight:500;line-height:24px;text-overflow:ellipsis;white-space:nowrap}.handout-sidebar-close{display:flex;width:28px;height:28px;flex:none;align-items:center;justify-content:center;border:0;border-radius:8px;background:transparent;color:var(--tertiary-foreground);cursor:pointer}.handout-sidebar-close:hover,.handout-sidebar-close:focus-visible{background:var(--neutral-alpha-a500);outline:0}.handout-sidebar-close svg{width:14px;height:14px}.handout-sidebar-inner{width:100%;padding:20px 16px}.handout-sidebar-built-with{padding:0 16px 20px}.handout-sidebar-backdrop{position:fixed;z-index:20;inset:0;display:block;border:0;background:rgb(0 0 0 / 10%);opacity:0;visibility:hidden;cursor:default;transition:opacity .1s ease,visibility .1s ease}.handout-sidebar-backdrop.is-open{opacity:1;visibility:visible}.handout-mobile-bar{position:sticky;z-index:10;top:0;display:flex;height:44px;align-items:center;gap:8px;padding:0 12px;border-bottom:1px solid var(--border-subtle);background:var(--background)}.handout-mobile-menu{display:flex;width:28px;height:28px;flex:none;align-items:center;justify-content:center;border:0;border-radius:8px;background:transparent;color:var(--tertiary-foreground);cursor:pointer}.handout-mobile-menu:hover,.handout-mobile-menu:focus-visible{background:var(--neutral-alpha-a500);outline:0}.handout-mobile-menu svg{width:14px;height:14px}.handout-mobile-bar>span{min-width:0;overflow:hidden;font-size:16px;font-weight:500;text-overflow:ellipsis;white-space:nowrap}.handout-document{padding:36px 20px 96px}.handout-page-title-heading{font-size:28px}}
@media(prefers-reduced-motion:reduce){.handout-site *,.handout-document-editor *{scroll-behavior:auto!important;transition:none!important}}
`;
