import { SITE_MOBILE_BREAKPOINT_PX } from "@lightsite/design-tokens";

/**
 * Canonical visual contract for editable, previewed, and published site content.
 * Keep editor-only affordances out of this stylesheet.
 */
export const SITE_DOCUMENT_CSS = `
[data-ls-public-site],[data-ls-public-site] *,.ls-document-editor,.ls-document-editor *{box-sizing:border-box}
html[data-ls-public-site],body[data-ls-public-site]{margin:0;min-height:100%;background:var(--background);color:var(--foreground);font-family:"Geist Variable","Geist",ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;letter-spacing:-.02em}
:where(.ls-site) button,:where(.ls-site) a{font:inherit}:where(.ls-site) a{color:inherit}
.ls-site,.ls-document-editor{background:var(--background);color:var(--foreground);font-family:"Geist Variable","Geist",ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;letter-spacing:-.02em}
.ls-site{display:flex;min-height:100svh}
.ls-sidebar{position:sticky;top:0;width:289px;height:100svh;flex:none;padding:26px 24px;background:var(--background)}
.ls-sidebar-inner{display:flex;width:241px;flex-direction:column;gap:16px}
.ls-sidebar-mobile-header,.ls-sidebar-backdrop{display:none}
.ls-editor-sidebar-desktop{display:block}.ls-editor-mobile-bar{display:none}.ls-editor-sidebar-content{width:241px}
/* PUBLISHED-SITE PARITY: Keep these sidebar rules aligned with EditorSiteSidebar.
   Preview and deployed sites both consume this canonical stylesheet. */
.ls-sidebar-section{display:flex;min-width:0;flex-direction:column;gap:8px}.ls-sidebar-section>h2{height:26px;min-width:0;margin:0;overflow:hidden;color:var(--muted-foreground);font-size:14px;font-weight:500;line-height:24px;text-overflow:ellipsis;white-space:nowrap}
.ls-sidebar-section>div{display:flex;flex-direction:column;gap:4px}
.ls-sidebar-row{display:flex;width:100%;height:36px;align-items:center;gap:8px;padding:0 10px;border:0;border-radius:8px;background:transparent;color:var(--foreground);font-size:16px;line-height:24px;text-align:left;text-decoration:none;cursor:pointer;transition:background .15s ease}
.ls-sidebar-row:hover,.ls-sidebar-row:focus-visible,.ls-sidebar-row.is-active{background:var(--accent);outline:0}.ls-tab{color:var(--tertiary-foreground)}.ls-sidebar-row.is-active{color:var(--secondary-foreground)}.ls-sidebar-row svg{width:16px;height:16px;flex:none;color:var(--tertiary-foreground)}.ls-tab svg{color:inherit}.ls-sidebar-row span{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.ls-sidebar-button{display:flex;min-height:36px;align-items:center;justify-content:center;padding:6px 12px;border:1px solid var(--border);border-radius:10px;font-size:15px;font-weight:500;line-height:20px;text-align:center;text-decoration:none;transition:background .15s ease}
.ls-sidebar-button-filled{border-color:transparent;background:var(--primary);color:var(--primary-foreground)}.ls-sidebar-button-outline{background:var(--background)}.ls-sidebar-button:hover{filter:brightness(.94)}
.ls-sidebar-section-buttons>div{gap:8px}
.ls-main{display:flex;min-width:0;min-height:100svh;flex:1;flex-direction:column}.ls-mobile-bar{display:none}.ls-document{width:100%;flex:1;padding:54px 52px 128px}
.ls-document,.ls-document-editor{font-weight:325}
.ls-page-panel{width:612px;max-width:100%;margin:0 auto;container-type:inline-size}.ls-page-panel[hidden]{display:none}
.ls-prosemirror{min-height:100%;outline:none}.ls-prosemirror>*{width:100%;margin:0}
.ls-prosemirror>*+*{margin-top:20px}
.ls-prosemirror>h1+p,.ls-prosemirror>h2+p,.ls-prosemirror>h3+p{margin-top:14px}
.ls-prosemirror>blockquote,.ls-prosemirror>pre,.ls-prosemirror>ul,.ls-prosemirror>ol{margin-top:24px}
.ls-prosemirror>h1:not(:first-child){margin-top:72px}.ls-prosemirror>h2:not(:first-child){margin-top:50px}.ls-prosemirror>h3:not(:first-child){margin-top:36px}
.ls-prosemirror>p{padding:0;color:var(--tertiary-foreground);font-size:16px;font-weight:325;font-variation-settings:"wght" 325;line-height:26px;white-space:pre-wrap}
.ls-prosemirror>h1{padding:0;color:var(--foreground);font-size:24px;font-weight:500;letter-spacing:-.03em;line-height:36px;white-space:pre-wrap}
.ls-prosemirror>h2{padding:0;color:var(--foreground);font-size:20px;font-weight:500;letter-spacing:-.03em;line-height:32px;white-space:pre-wrap}
.ls-prosemirror>h3{padding:0;color:var(--foreground);font-size:16px;font-weight:500;letter-spacing:-.03em;line-height:26px;white-space:pre-wrap}
.ls-prosemirror>ul,.ls-prosemirror>ol{padding:0 0 0 24px;color:var(--tertiary-foreground);font-size:16px;line-height:26px}.ls-prosemirror>ul{list-style:disc}.ls-prosemirror>ol{list-style:decimal}.ls-prosemirror li p{margin:0}
.ls-blockquote{padding:6px 0 6px 16px;border-left:4px solid var(--border);color:var(--muted-foreground);font-size:16px;line-height:26px}
.ls-task-list{display:flex;flex-direction:column;gap:6px;padding:0!important;list-style:none!important}.ls-task-item{display:flex;align-items:flex-start;gap:8px}.ls-task-check{display:flex;width:16px;height:16px;flex:none;align-items:center;justify-content:center;margin-top:5px;border:1px solid var(--border);border-radius:4px;font-size:11px}.ls-task-item[data-checked=true]>div{color:var(--muted-foreground);text-decoration:line-through}
.ls-code-block{overflow:auto;padding:16px;border:1px solid var(--border);border-radius:8px;background:var(--muted);color:var(--foreground);font-size:14px;line-height:24px}.ls-inline-code{padding:2px 6px;border:1px solid var(--border);border-radius:6px;background:var(--muted);color:var(--foreground);font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:.875em}
.ls-divider{height:24px;margin-top:36px!important;border:0;background:linear-gradient(to bottom,transparent calc(50% - .5px),var(--border) calc(50% - .5px),var(--border) calc(50% + .5px),transparent calc(50% + .5px))}
.ls-page-title{display:flex;flex-direction:column;align-items:center;gap:24px;padding:52px 0 36px;border-bottom:1px solid var(--border);text-align:center}.ls-page-title[data-align=left]{align-items:flex-start;text-align:left}
.ls-page-title-logos{display:flex;flex-wrap:wrap;align-items:center;justify-content:center;gap:8px}.ls-page-title[data-align=left] .ls-page-title-logos{justify-content:flex-start}
.ls-page-title-logo{display:flex;width:52px;height:52px;align-items:center;justify-content:center;overflow:hidden;border-radius:14px;background:var(--foreground);color:var(--background)}.ls-page-title-logo img{width:100%;height:100%;padding:8px;object-fit:contain}.ls-logo-connector{display:none}
.ls-page-title-copy{width:100%}.ls-page-title-heading{max-width:100%;margin:0;color:var(--foreground);font-size:28px;font-weight:500;letter-spacing:-.03em;line-height:1}.ls-page-title-subtitle{max-width:100%;margin:8px 0 0;color:var(--tertiary-foreground);font-size:16px;font-weight:325;font-variation-settings:"wght" 325;line-height:1.5}
.ls-icon-list{display:flex;flex-direction:column;gap:6px;padding:0!important;list-style:none!important}.ls-icon-list-item{display:grid;grid-template-columns:20px minmax(0,1fr);align-items:start;gap:8px}.ls-icon-list-item>div{min-width:0;color:var(--tertiary-foreground);font-size:16px;line-height:26px}.ls-icon-tile{display:flex;width:20px;height:20px;align-items:center;justify-content:center;margin-top:3px;color:var(--muted-foreground)}.ls-icon-tile svg{width:14px;height:14px}
[data-icon-color=neutral]{color:var(--muted-foreground)}[data-icon-color=purple]{color:var(--purple-foreground)}[data-icon-color=blue]{color:var(--blue-foreground)}[data-icon-color=cyan]{color:var(--cyan-foreground)}[data-icon-color=teal]{color:var(--teal-foreground)}[data-icon-color=green]{color:var(--green-foreground)}[data-icon-color=yellow]{color:var(--yellow-foreground)}[data-icon-color=orange]{color:var(--orange-foreground)}[data-icon-color=red]{color:var(--red-foreground)}[data-icon-color=pink]{color:var(--pink-foreground)}
.ls-image-block{overflow:hidden;border-radius:10px}.ls-image-block img{display:block;width:100%;height:auto;max-height:680px;object-fit:contain}
.ls-image-card{display:grid;grid-template-columns:minmax(180px,41.5%) minmax(0,1fr);align-items:center;gap:20px;overflow:hidden;padding:6px;border:1px solid var(--border);border-radius:14px;background:var(--card);color:var(--foreground)}.ls-image-card-media{display:block;align-self:center;overflow:hidden;border-radius:10px;line-height:0}.ls-image-card-media img{display:block;width:100%;height:auto;border-radius:10px;object-fit:contain}.ls-image-card-copy{display:flex;min-width:0;flex-direction:column;align-items:flex-start;justify-content:center;padding:20px}.ls-card-title,[data-lightsite-icon-card-title],[data-lightsite-image-card-title]{margin:0;color:var(--foreground);font-size:16px;font-weight:500;line-height:24px}.ls-card-body,[data-lightsite-icon-card-body],[data-lightsite-image-card-body]{margin:0;color:var(--tertiary-foreground);font-size:14px;line-height:24px}.ls-small-button{display:inline-flex;width:max-content;height:30px;align-items:center;justify-content:center;margin-top:12px;padding:0 10px;border:1px solid var(--border);border-radius:8px;color:var(--foreground);font-size:14px;font-weight:500;text-decoration:none}
.ls-icon-card{padding:16px;border:1px solid var(--border);border-radius:12px;background:var(--card);color:var(--foreground)}.ls-card-icon{display:flex;width:32px;height:32px;align-items:center;justify-content:center;margin-bottom:12px;border-radius:8px;background:var(--accent);color:var(--muted-foreground)}.ls-card-icon svg{width:18px;height:18px}.ls-card-copy{min-width:0}.ls-card-title,[data-lightsite-icon-card-title],[data-lightsite-image-card-title],.ls-logo-grid-title,[data-lightsite-logo-grid-title]{letter-spacing:-.03em}
.ls-testimonial{display:grid;grid-template-columns:40px minmax(0,1fr);grid-template-rows:20px 20px minmax(40px,auto);column-gap:12px;align-items:center;padding:16px 20px 20px 16px;border:1px solid var(--border);border-radius:14px;background:var(--card);color:var(--foreground)}.ls-testimonial-avatar{display:flex;width:40px;height:40px;align-items:center;justify-content:center;overflow:hidden;grid-column:1;grid-row:1 / span 2;border:1px solid var(--border);border-radius:10px;background:var(--muted)}.ls-testimonial-avatar img{width:100%;height:100%;object-fit:cover}.ls-testimonial-avatar svg{width:18px;height:18px}.ls-testimonial>div{display:contents}.ls-testimonial-name,[data-lightsite-testimonial-author-name]{min-width:0;margin:0;overflow:hidden;grid-column:2;grid-row:1;color:var(--foreground);font-size:16px;font-weight:500;line-height:20px;text-overflow:ellipsis;white-space:nowrap}.ls-testimonial-role,[data-lightsite-testimonial-author-role]{min-width:0;margin:0;overflow:hidden;grid-column:2;grid-row:2;color:var(--tertiary-foreground);font-size:14px;line-height:20px;text-overflow:ellipsis;white-space:nowrap}.ls-testimonial-quote,[data-lightsite-testimonial-quote]{min-height:40px;margin:0;padding-top:16px;grid-column:1 / -1;grid-row:3;color:var(--foreground);font-size:18px;font-weight:500;line-height:24px}.ls-testimonial-quote:before,[data-lightsite-testimonial-quote]:before{content:"\\201C"}.ls-testimonial-quote:after,[data-lightsite-testimonial-quote]:after{content:"\\201D"}
.ls-logo-grid{display:grid;width:100%;min-width:0;max-width:100%;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;padding:6px}.ls-logo-grid-item{display:flex;min-width:0;flex-direction:column;align-items:center;gap:8px;padding:16px 12px 12px;border:1px solid var(--border);border-radius:14px;background:var(--background);color:var(--foreground);text-align:center}.ls-logo-grid-image{display:flex;width:40px;height:40px;align-items:center;justify-content:center;overflow:hidden;border-radius:10px}.ls-logo-grid-image img{width:100%;height:100%;object-fit:contain}.ls-logo-grid-image svg{width:20px;height:20px}.ls-logo-grid-title,[data-lightsite-logo-grid-title]{margin:0;color:var(--foreground);font-size:16px;font-weight:500;line-height:24px}
.ls-button-block{display:inline-flex;width:max-content;min-height:32px;max-width:100%;align-items:center;justify-content:center;padding:0 12px;border-radius:8px;background:var(--primary);color:var(--primary-foreground);font-size:15px;font-weight:500;line-height:20px;text-align:center;text-decoration:none;box-shadow:0 0 0 1px color-mix(in oklab,var(--primary) 16%,transparent)}.ls-button-block:hover{background:color-mix(in oklab,var(--primary) 88%,var(--background))}.ls-button-block-full{display:flex;width:100%;min-height:40px;padding:2px 12px}
.ls-embed{width:100%;overflow:hidden;border:1px solid var(--border);border-radius:12px;background:var(--muted)}.ls-embed iframe{width:100%;height:100%;border:0}
.ls-grid{display:flex;flex-direction:column;gap:12px}.ls-grid-row{display:grid;grid-template-columns:repeat(var(--lightsite-grid-columns),minmax(0,1fr));gap:12px}.ls-grid-cell{min-width:0;padding:16px;border:1px solid var(--border);border-radius:12px;background:var(--card)}
@container (max-width:520px){.ls-image-card{grid-template-columns:1fr;gap:0}.ls-image-card-copy{min-height:80px;padding:16px}.ls-logo-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.ls-grid-row{grid-template-columns:1fr}}
@container (max-width:340px){.ls-logo-grid{grid-template-columns:1fr}}
.ls-table-scroll{overflow-x:auto}.ls-table{width:100%;border:1px solid var(--border);border-collapse:separate;border-spacing:0;border-radius:10px;background:var(--card)}.ls-table th,.ls-table td{padding:10px 12px;border-right:1px solid var(--border);border-bottom:1px solid var(--border);color:var(--tertiary-foreground);font-size:14px;line-height:22px;text-align:left;vertical-align:top}.ls-table th{background:var(--table-header-background);color:var(--foreground);font-weight:500}.ls-table tr>*:last-child{border-right:0}.ls-table tr:last-child>*{border-bottom:0}
.ls-link{color:var(--link);text-underline-offset:2px}.ls-footer{display:flex;align-items:center;justify-content:center;gap:8px;padding:26px;color:var(--tertiary-foreground);font-size:12px}.ls-footer-logo{display:block;width:83px;height:17px;flex:none;background:var(--tertiary-foreground);-webkit-mask:url("/lightsite-logo.svg") center/contain no-repeat;mask:url("/lightsite-logo.svg") center/contain no-repeat}.ls-empty-page{padding:80px 0;text-align:center}.ls-empty-page h1{font-size:20px}
/* The editor uses richer node-view wrappers, but the presentation contract remains identical. */
.ls-document-editor .ls-prosemirror{width:100%;min-width:0;max-width:100%;padding-top:54px;padding-bottom:128px}
.ls-document-editor .ls-prosemirror>p,.ls-document-editor .ls-prosemirror>h1,.ls-document-editor .ls-prosemirror>h2,.ls-document-editor .ls-prosemirror>h3,.ls-document-editor .ls-prosemirror>ul,.ls-document-editor .ls-prosemirror>ol,.ls-document-editor .ls-prosemirror>blockquote,.ls-document-editor .ls-prosemirror>pre,.ls-document-editor .ls-prosemirror>hr,.ls-document-editor .ls-prosemirror>.react-renderer,.ls-document-editor .ls-prosemirror>[data-lightsite-grid],.ls-document-editor .ls-prosemirror>.tableWrapper{width:min(612px,calc(100% - 104px));max-width:calc(100% - 104px);margin-right:auto;margin-left:auto}
.ls-document-editor .ls-prosemirror>*+*{margin-top:20px}.ls-document-editor .ls-prosemirror>h1+p,.ls-document-editor .ls-prosemirror>h2+p,.ls-document-editor .ls-prosemirror>h3+p{margin-top:14px}.ls-document-editor .ls-prosemirror>blockquote,.ls-document-editor .ls-prosemirror>pre,.ls-document-editor .ls-prosemirror>ul,.ls-document-editor .ls-prosemirror>ol{margin-top:24px}.ls-document-editor .ls-prosemirror>h1:not(:first-child){margin-top:72px}.ls-document-editor .ls-prosemirror>h2:not(:first-child){margin-top:50px}.ls-document-editor .ls-prosemirror>h3:not(:first-child){margin-top:36px}
.ls-document-editor .ls-prosemirror>p{padding:0;color:var(--tertiary-foreground);font-size:16px;font-weight:325;font-variation-settings:"wght" 325;line-height:26px}.ls-document-editor .ls-prosemirror>h1{padding:0;color:var(--foreground);font-size:24px;font-weight:500;letter-spacing:-.03em;line-height:36px}.ls-document-editor .ls-prosemirror>h2{padding:0;color:var(--foreground);font-size:20px;font-weight:500;letter-spacing:-.03em;line-height:32px}.ls-document-editor .ls-prosemirror>h3{padding:0;color:var(--foreground);font-size:16px;font-weight:500;letter-spacing:-.03em;line-height:26px}.ls-document-editor .ls-prosemirror>ul,.ls-document-editor .ls-prosemirror>ol{padding:0 0 0 24px;color:var(--tertiary-foreground);font-size:16px;line-height:26px}
.ls-document-editor .lightsite-editor-page-title-shell{display:flex;flex-direction:column;align-items:center;gap:24px;padding:52px 0 36px;border-bottom:1px solid var(--border);text-align:center}.ls-document-editor .lightsite-editor-page-title-shell[data-align=left]{align-items:flex-start;text-align:left}.ls-document-editor .lightsite-editor-page-title{display:contents}.ls-document-editor .lightsite-editor-page-title-content>[data-node-view-content-react],.ls-document-editor .lightsite-editor-logo-grid>[data-node-view-content-react]{display:contents}.ls-document-editor .lightsite-editor-page-title-content [data-lightsite-page-title-heading]{color:var(--foreground);font-size:28px;font-weight:500;letter-spacing:-.03em;line-height:1}.ls-document-editor .lightsite-editor-page-title-content [data-lightsite-page-title-subtitle]{color:var(--tertiary-foreground);font-size:16px;font-weight:325;font-variation-settings:"wght" 325;letter-spacing:-.02em;line-height:1.5}
.ls-document-editor .lightsite-editor-button-block{min-height:32px;padding:0 12px;border-radius:8px;background:var(--primary);color:var(--primary-foreground);font-size:15px;font-weight:500;line-height:20px;box-shadow:0 0 0 1px color-mix(in oklab,var(--primary) 16%,transparent)}
.ls-document-editor .lightsite-editor-button-block-full{min-height:40px;padding:2px 12px}
.ls-document-editor .lightsite-editor-card-content :where(h1,h2,h3),.ls-document-editor .lightsite-editor-card-content [data-lightsite-icon-card-title],.ls-document-editor .lightsite-editor-card-content [data-lightsite-image-card-title]{color:var(--foreground);letter-spacing:-.03em}.ls-document-editor .lightsite-editor-card-content :where(p),.ls-document-editor .lightsite-editor-card-content [data-lightsite-icon-card-body],.ls-document-editor .lightsite-editor-card-content [data-lightsite-image-card-body]{color:var(--tertiary-foreground)}.ls-document-editor .lightsite-editor-logo-grid-title-content [data-lightsite-logo-grid-title]{letter-spacing:-.03em}
@media(max-width:${SITE_MOBILE_BREAKPOINT_PX}px){.ls-editor-sidebar-desktop{display:none}.ls-editor-mobile-bar{display:flex}.ls-editor-sidebar-content{width:100%}body.ls-drawer-open{overflow:hidden}.ls-site{display:block}.ls-sidebar{position:fixed;z-index:30;top:0;left:0;width:min(289px,86vw);height:100svh;padding:0;border-right:1px solid var(--border);background:var(--background);box-shadow:0 16px 40px rgb(0 0 0 / 18%);visibility:hidden;transform:translateX(-100%);transition:transform .2s ease,visibility .2s ease}.ls-sidebar.is-open{visibility:visible;transform:translateX(0)}.ls-sidebar-mobile-header{display:flex;height:44px;align-items:center;gap:8px;padding:0 8px 0 16px;border-bottom:1px solid var(--border-subtle)}.ls-sidebar-mobile-title{min-width:0;flex:1;overflow:hidden;color:var(--tertiary-foreground);font-size:16px;font-weight:500;line-height:24px;text-overflow:ellipsis;white-space:nowrap}.ls-sidebar-close{display:flex;width:28px;height:28px;flex:none;align-items:center;justify-content:center;border:0;border-radius:8px;background:transparent;color:var(--tertiary-foreground);cursor:pointer}.ls-sidebar-close:hover,.ls-sidebar-close:focus-visible{background:var(--neutral-alpha-a500);outline:0}.ls-sidebar-close svg{width:14px;height:14px}.ls-sidebar-inner{width:100%;padding:20px 16px}.ls-sidebar-backdrop{position:fixed;z-index:20;inset:0;display:block;border:0;background:rgb(0 0 0 / 10%);opacity:0;visibility:hidden;cursor:default;transition:opacity .1s ease,visibility .1s ease}.ls-sidebar-backdrop.is-open{opacity:1;visibility:visible}.ls-mobile-bar{position:sticky;z-index:10;top:0;display:flex;height:44px;align-items:center;gap:8px;padding:0 12px;border-bottom:1px solid var(--border-subtle);background:var(--background)}.ls-mobile-menu{display:flex;width:28px;height:28px;flex:none;align-items:center;justify-content:center;border:0;border-radius:8px;background:transparent;color:var(--tertiary-foreground);cursor:pointer}.ls-mobile-menu:hover,.ls-mobile-menu:focus-visible{background:var(--neutral-alpha-a500);outline:0}.ls-mobile-menu svg{width:14px;height:14px}.ls-mobile-bar>span{min-width:0;overflow:hidden;font-size:16px;font-weight:500;text-overflow:ellipsis;white-space:nowrap}.ls-document{padding:36px 20px 96px}.ls-page-title{padding-top:20px}.ls-page-title-heading{font-size:28px}}
@media(prefers-reduced-motion:reduce){.ls-site *,.ls-document-editor *{scroll-behavior:auto!important;transition:none!important}}
`;
